# Copyright (c) 2026 Semillero de Investigación en Recursos Educativos Digitales Abiertos
services:
  # Imagen de Apache, este es nuestro servidor web
  web:
    image: afestupinanp/taller-unad-sireda:latest
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./src:/var/www:rw
    networks:
      - app
    ports:
      - 80:80
      - 443:443
      - 5173:5173
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
  # Imagen de base de datos. Esta es nuestra base de datos.
  db:
    container_name: db
    image: mariadb:lts
    env_file:
      - src/.env
    networks:
      - app
    volumes:
      - dbvolume:/var/lib/mysql:rw
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
  # Imagen de visor de base de datos.
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.3-apache
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - app
    ports:
      - 8080:80
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

# Nuestro volumen para base de datos.
volumes:
  dbvolume:

# Nuestra red. Esto permite que las imágenes puedan verse entre si.
networks:
  app: