# Copyright (c) 2024 Semillero de Investigación en Recursos Educativos Digitales Abiertos
version: '3.7'
services:
  # Imagen de Apache, este es nuestro servidor web
  web:
    image: afestupinanp/taller-unad-sireda:latest
    container_name: web
    build: .
    volumes:
      - ./src:/var/www:rw
    networks:
      - app
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
  # Imagen de base de datos. Esta es nuestra base de datos.
  db:
    container_name: db
    image: mariadb:lts
    env_file:
      - src/.env
    networks:
      - app
    volumes:
      - dbvolume:/var/lib/mysql:rw
    ports:
      - 3306:3306
  # Imagen de visor de base de datos.
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.1-apache
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - app
    ports:
      - 8080:80
    depends_on:
      - db

# Nuestro volumen para base de datos.
volumes:
  dbvolume:

# Nuestra red. Esto permite que las imágenes puedan verse entre si.
networks:
  app: